### ISSUE TITLE
no context menu when using with FF v42

### ISSUE THREAD

**Issue by christianse2** [joao-carloto/FireRobot#80]
Hi João,
are you still working on this plugin? I like both the FF plugin as well as your powershell script. I'm just evaluating RF and wanted to see how your plugin works.

I installed 1.1.3 and it seems to work for most parts but after selecting items on the page a right-click only shows a tiny square instead of the contect menu.

**Comment by joao-carloto** [comment]
Hi christianse2, thanks for the feedback.

I just tried it in FF 42, both on windows 8, 64 bit and Ubuntu 32 bit. I have currently no access to  an OSx machine so I'm currently not supporting it. There were some GUI issues last time I checked in OSx, but it was usable.
I could not reproduce the problem. 
However, I could reproduce this situation, some time ago, when trying to use this plugin on FF Dev Edition.
Could you provide more details about the OS you are using? Was it working on a previous version of FF?

Regarding the question if I'm still working on the plugin: This project is stalled because it's waiting for more than 6 months to be reviewed by the Mozilla staff. If it's not reviewed  and signed by the time FF 44 comes out, nobody will be able to use it. You can see the details at this link: https://blog.mozilla.org/addons/2015/09/23/add-ons-update-71/comment-page-1/#comment-220043
Since the Mozilla staff is not eager to solve the problem, I'm considering converting this to a Chrome Browser extension. Since the APIs available on Chrome are not the same, the new plugin may not have the same set of functionalities. I hope I have it ready by beginning of next year, but I can't give you a schedule.

**Comment by christianse2** [comment]
You're right. It looks like one of the plugins is causing the issue on my side. I setup an extra ubuntu environment and don't have any problems there.
I can hear your frustration with getting the plugin reviewed... it would help getting more user using it and providing feedback.
